---
name: AI Issue Responder

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  ai-respond:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Download AI responder script
        run: |
          curl -sSL "https://raw.githubusercontent.com/dmzoneill/dmzoneill/main/ai-responder.py" -o ai-responder.py
          chmod +x ai-responder.py

      - name: Run AI responder
        env:
          OPENAI_API_KEY: ${{ secrets.AI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_REPO_URL: "https://github.com/${{ github.repository }}"
        run: ./ai-responder.py
