---
name: AI Issue Responder

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  ai-respond:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Get issue content
        id: get_issue
        run: |
          echo "title=${{ github.event.issue.title }}" >> "$GITHUB_OUTPUT"
          echo "body=${{ github.event.issue.body }}" >> "$GITHUB_OUTPUT"

      - name: Call OpenAI API
        id: ai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          prompt="You're a helpful AI assistant. " 
          prompt+="Reply concisely to the following GitHub issue."

          title="${{ steps.get_issue.outputs.title }}"
          body="${{ steps.get_issue.outputs.body }}"

          json=$(jq -n \
            --arg model "gpt-4o" \
            --arg system "$prompt" \
            --arg user "$title - $body" \
            '{
              model: $model,
              messages: [
                {role: "system", content: $system},
                {role: "user", content: $user}
              ],
              temperature: 0.5
            }')

          api_url="https://api.openai.com/v1/chat/completions"
          auth="Authorization: Bearer $OPENAI_API_KEY"
          ctype="Content-Type: application/json"

          response=$(curl -s "$api_url" \
            -H "$auth" \
            -H "$ctype" \
            -d "$json" | jq -r '.choices[0].message.content')

          echo "reply=$response" >> "$GITHUB_OUTPUT"

      - name: Reply to issue
        run: |
          comment="${{ steps.ai.outputs.reply }}"
          api_url="https://api.github.com/repos/${{ github.repository }}"
          api_url+="/issues/${{ github.event.issue.number }}/comments"

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$api_url" \
            -d "$(jq -n --arg body "$comment" '{body: $body}')"
